package gnupiano;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.runners.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class NoteGeneratorTest {
//	@InjectMocks
//	private NoteGenerator noteGenerator;

	@Test
	public void testNoteGenerator() throws Exception {
		return;
	}

	@Test
	public void testGetPitchFromLevel() throws Exception {
		return;
	}

	@Test
	public void testGetIndexFromPitch() throws Exception {
		return;
	}

	@Test
	public void testGetRowsDistance() throws Exception {
		return;
	}

	@Test
	public void testGetRowsDistanceFromClefs() throws Exception {
		return;
	}

	@Test
	public void testGetClefsNumber() throws Exception {
		return;
	}

	@Test
	public void testReset() throws Exception {
		return;
	}

	@Test
	public void testUpdate() throws Exception {
		return;
	}

	@Test
	public void testSetNotesList() throws Exception {
		return;
	}

	@Test
	public void testGetClefMask() throws Exception {
		return;
	}

	@Test
	public void testGetPitchFromClefAndLevel() throws Exception {
		return;
	}

	@Test
	public void testAddRange() throws Exception {
		return;
	}

	@Test
	public void testGetNotesNumber() throws Exception {
		return;
	}

	@Test
	public void testGetFirstLowPitch() throws Exception {
		return;
	}

	@Test
	public void testGetFirstHighPitch() throws Exception {
		return;
	}

	@Test
	public void testGetSecondLowPitch() throws Exception {
		return;
	}

	@Test
	public void testGetSecondHighPitch() throws Exception {
		return;
	}

	@Test
	public void testGetAlteration() throws Exception {
		return;
	}

	@Test
	public void testGetAlteredFromBase() throws Exception {
		return;
	}

	@Test
	public void testGetRhythmPitch() throws Exception {
		return;
	}

	@Test
	public void testGetRandomNote() throws Exception {
		return;
	}

	@Test
	public void testGetTripletRandomNote() throws Exception {
		return;
	}

	@Test
	public void testGetRandomSequence() throws Exception {
		return;
	}

	@Test
	public void testGetRandomChordOrInterval() throws Exception {
		return;
	}

}
